import day_07
import simplifile

pub fn check_beam_split_test() {
  assert ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."
    |> day_07.check_beam_split
    == 21
}

pub fn calculate_distances_for_real_test() {
  let assert Ok(file) = simplifile.read("input/day_07")

  assert file
    |> day_07.check_beam_split
    == 1656
}
